### PR TITLE
[GPII-4107]: Upgrade cert-manager to v0.11.0

### PR DESCRIPTION
**Pull request by natarajaya**
Summary of changes:
* Upgraded `cert-manager` chart to [v0.11.0](https://github.com/jetstack/cert-manager/releases/tag/v0.11.0)
* CRDs for some reason [provided separately](https://github.com/jetstack/cert-manager/blob/v0.11.0/deploy/manifests), I included them into the Chart.
*  CRDs describe `serviceAccountSecretRef` atrribute of `clouddns` type solver as required, which makes impossible to pass resource validation without providing SA credentials. I corrected the CRDs to allow us to use "ambient credentials" available on GKE. Should we propose this to upstream?
* Updated `flowmanager` Issuer and Certificate resources.

Deployment plan:
- [ ] Merge this PR.
- [ ] Wait for version updater commit.
- [ ] Start a pipeline.
- [ ] For all non-ephemeral envs, repeat [migration steps](https://github.com/gpii-ops/gpii-infra/blob/193b44cc758b9e16a323b28f1ced8a31db6b5ab9/gcp/README.md#error-appkubernetesionamecert-manager-matchexpressionsv1labelselectorrequirementnil-field-is-immutable). This should be non-disruptive, so no downtime is required.

### CODE REVIEW

**Comment by natarajaya** [comment]
Updated PR description with deployment plan. Still can't decide if it is worth it to move cert-manager CRDs into separate chart.

**Comment by stepanstipl** [comment]
Thanks @natarajaya. It looks good overall, but before moving into a more in-detail review, a few questions:

Have you considered if we can avoid manual steps in the deployment? I think this would be beneficial for the users. (I believe this can be done by either not changing the `selector` on the deployment, or perhaps easier by renaming the deployment or the whole Helm release.)

> if it is worth it to move cert-manager CRDs into separate chart.

I would vote for yes, this will allow us a bit of flexibility next time we need to update CRDs, let's take a scenario:
- Deploy a new version of CRDs
- Update apps to use the new CRDs
- Deploy a new version of cert-manager
- Delete the old version of CRDs

Without having CRDs in a separate chart this would not be possible without a downtime and would require manual intervention.

>  Should we propose this to upstream?

Yes, this is a good catch worth proposing upstream.

**Comment by natarajaya** [comment]
@stepanstipl Thanks for the review!

> Have you considered if we can avoid manual steps in the deployment?

This is a one-time migration with 4 steps that take less than 5 minutes to complete. Also, we try to encourage developers to not keep their environments running for extended periods of time, with `rake destroy_hard && rake` as universal approach to problem solving. I don't think automation is needed here.

> And will the current, old, CRDs be cleaned up? 

Yes, point 4 of the migration scenario deletes orphaned CRDs.

> Without having CRDs in a separate chart this would not be possible without a downtime and would require manual intervention.

But current implementation does not have CRDs in a separate chart and does not require any downtime. Manual intervention would be needed in both cases, because Helm likes to leave old CRDs behind. I am not convinced so far.

**Comment by natarajaya** [comment]
> Yes, this is a good catch worth proposing upstream.

Looks like PR is already open to address that:
https://github.com/jetstack/cert-manager/pull/2250

**Comment by stepanstipl** [comment]
>> Have you considered if we can avoid manual steps in the deployment?

> This is a one-time migration with 4 steps that takes less than 5 minutes to complete. Also, we try to encourage developers to not keep their environments running for extended periods of time, with rake destroy_hard && rake as universal approach to migration problems. I don't think automation is needed here.

Every developer upgrading a cluster will hit this error and will have to either find out or ask for support to solve this problem, spending more than 5 minutes of his/hers time on this, and our time as well. Completely destroying and recreating cluster also takes significant time, it should bot be **the default** approach.

I would consider options on how to do this automatically, especially if the solution could be as simple as changing the chart's name. (It's probably `1h+ time * number_of_developers` on one side vs. probably less than 1h of one person to fix and test this change).

_Imagine how we would like Google requiring us to recreate a cluster, or hit an error and have to go to docs and find a solution with a set of manual steps to perform, for every application update?_

>> And will the current, old, CRDs be cleaned up?

> Yes, point 4 of the migration scenario deletes orphaned CRDs.

Thanks 👍 , I missed that. 

>> Without having CRDs in a separate chart this would not be possible without a downtime and would require manual intervention.

> But current implementation does not have CRDs in a separate chart and does not require any downtime. Manual intervention would be needed in both cases, because Helm likes to leave old CRDs behind. I am not convinced so far.

Manual intervention wouldn't be needed if the CRDs are deployed without the `crd-install` hook, Helm would clear these up.

**Comment by natarajaya** [comment]
> Completely destroying and recreating cluster also takes significant time, it should bot be the default approach.

@stepanstipl I think we talked about this before and have not found the consensus :) I recreate my dev env multiple times per day and have no issues with this process whatsoever. Of course there are corner cases (like regional keyring migration #329), where changes block normal destroy / deploy operations, but this is not the one.

> especially if the solution could be as simple as changing the chart's or deployment's name.

Unfortunately it is not that simple. Manual actions would still be required to clean up orphaned Flowmanager resources and CRDs.

> Imagine how we would like Google requiring us to recreate a cluster, or hit an error and have to go to docs and find a solution with a set of manual steps to perform, for every application update?

I understand your point here, but don't think it is valid to compare Google with millions of GCP customers and our small team. Different scale = different solutions. 

> Manual intervention wouldn't be needed if the CRDs are deployed without the crd-install hook, Helm would clear these up.

I tested the following scenario with the new CRDs (kept in cert-manager chart and installed without hook):
* Renamed `certificates.cert-manager.io` -> `newcertificates.cert-manager.io`
* Bumped `cert-manager` chart version.
* Updated Certificate resource in `flowmnager` chart.
* Bumped `flowmanager` chart version.

After that I run `rake` – it completed successfully on first try with the following results:
* Old `certificates.cert-manager.io` CRD got removed.
* Old `flowmanager` Certificate resource removed.
* New `newcertificates.cert-manager.io` CRD created.
* New `flowmanager` Certificate resource created.

So no manual intervention is required as well, even if we leave CRDs as they are now.

**Comment by stepanstipl** [comment]
> Unfortunately it is not that simple. Manual actions would still be required to clean up orphaned Flowmanager resources and CRDs.
```hcl
locals {
  crds_to_remove = ["certificates","challenges","clusterissuers","issuers","orders"]
}

resource "null_resource" "remove_old_crds" {
  provisioner "local-exec" {
    command = "kubectl delete crd ${join(" ", formatlist("%s.certmanager.k8s.io", local.crds_to_remove))}"
  }
  depends_on = ["module.cert-manager"]
}
```

> Renamed certificates.cert-manager.io -> newcertificates.cert-manager.io
> ...
> So no manual intervention is required as well, even if we leave CRDs as they are now.
```
1 error occurred:
        * module.gpii-flowmanager.helm_release.release: 1 error occurred:
        * helm_release.release: rpc error: code = Unknown desc = failed decoding reader into objects: [unable to recognize "": no matches for kind "Certificate" in version "cert-manager.io/v1alpha2"
```

Helm will fail when trying to clean up the old CRD instances if it has been already removed. Changing just the CRD `metadata.name` is not sufficient to test this:

```diff
diff --git a/shared/charts/cert-manager/templates/crd.yaml b/shared/charts/cert-manager/templates/crd.yaml
index fb1d0bed..f4c33f34 100644
--- a/shared/charts/cert-manager/templates/crd.yaml
+++ b/shared/charts/cert-manager/templates/crd.yaml
@@ -1781,7 +1781,7 @@ apiVersion: apiextensions.k8s.io/v1beta1
 kind: CustomResourceDefinition
 metadata:
   creationTimestamp: null
-  name: certificates.cert-manager.io
+  name: certificates2.cert-manager.io
 spec:
   additionalPrinterColumns:
   - JSONPath: .status.conditions[?(@.type=="Ready")].status
@@ -1807,13 +1807,13 @@ spec:
     type: date
   group: cert-manager.io
   names:
-    kind: Certificate
+    kind: Certificate2
     listKind: CertificateList
-    plural: certificates
+    plural: certificates2
     shortNames:
     - cert
     - certs
-    singular: certificate
+    singular: certificate2
   scope: Namespaced
   subresources:
     status: {}
```

**Comment by natarajaya** [comment]
> depends_on = ["module.cert-manager"]

@stepanstipl You can't do that – old CRDs can be removed only after charts containing custom resources are upgraded, otherwise TF will throw the same `unable to recognize "": no matches for kind "Certificate"` errors. 

> Helm will fail when trying to clean up the old CRD instances if it has been already removed

Yes, it will fail indeed, but how moving CRDs to a separate chart going to change this?

**Comment by stepanstipl** [comment]
>> depends_on = ["module.cert-manager"]

> @stepanstipl You can't do that – old CRDs can be removed only after charts containing custom resources are upgraded, otherwise TF will throw the same unable to recognize "": no matches for kind errors.

Put it in the `flowmanager` or any other module that will run only after the flowmanager itself is updated.

> Yes, it will fail indeed, but how moving CRDs to a separate chart going to change this?

I put an example in my previous comment:
> - Deploy a new version of CRDs
> - Update apps to use the new CRDs
> - Deploy a new version of cert-manager
> - Delete the old version of CRDs

You would be able to do this because CRD updates are decoupled from cert-manager itself.

**Comment by natarajaya** [comment]
I tested number of automatic upgrade scenarios suggested by Stepan – all of them suffered from the same issue:
* Immutable fields on `cert-manager` deployment require release deletion.
* When release is deleted, old `cert-manager` CRDs are destroyed.
* Without old CRDs Helm can't resolve diff for `flowmanager`.

I also have not found any significant benefits of moving CRDs to a separate chart, since the same upgrade scenario can be done in multiple steps by changing CRDs (adding updated, deploying changes, removing old) in the same chart.

So team decided to stick with current implementation and manual upgrade scenario.

**Pull request merged**
