### PR TITLE
GPII-4006: Deploy "performant validation" changes.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-4006](https://issues.gpii.net/browse/GPII-4006) for details, including verification steps, dev availability, et cetera.

### CODE REVIEW

**Comment by mrtyler** [comment]
We need smoke test results from your dev env demonstrating that the performance problem that failed the deploy has been fixed.

(I thought I wrote this requirement somewhere more durable than Slack, but the only thing I can find is https://pad.gpii.net/mypads/?/mypads/group/architecture-meetings-94p29xe/pad/view/arch-2019-06-19-t9274nui line 127.)

**Comment by the-t-in-rtf** [comment]
@mrtyler, I did encounter a lone 503 error in a few runs (which @stepanstipl suggested was a known issue), but completed five runs without tripping the 300ms threshold. Here's a sample.

```
null_resource.locust_swarm_session (local-exec): Stats distribution:
null_resource.locust_swarm_session (local-exec): "Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
null_resource.locust_swarm_session (local-exec): "GET /preferences/carla",169,190,270,340,380,450,560,680,1100,1100
null_resource.locust_swarm_session (local-exec): "GET /preferences/nvda",183,190,270,340,370,450,520,610,660,890
null_resource.locust_swarm_session (local-exec): "GET /preferences/omar",199,220,300,360,390,510,640,790,900,1100
null_resource.locust_swarm_session (local-exec): "GET /preferences/vladimir",182,170,260,320,390,550,650,850,950,1200
null_resource.locust_swarm_session (local-exec): "GET /preferences/wayne",185,170,240,290,320,410,540,700,830,950
null_resource.locust_swarm_session (local-exec): "Total",918,180,270,330,370,480,570,700,850,1200
```

**Comment by mrtyler** [comment]
LGTM

**Comment by the-t-in-rtf** [comment]
Out of curiosity I went back through the [failed pipeline for the previous deploy](https://gitlab.com/gpii-ops/gpii-infra/-/jobs/230038475), here are the stats for that run:

```
Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",131,360,480,550,600,770,1000,1200,1300,1300
"GET /preferences/nvda",124,430,530,600,680,950,1000,1100,1300,1400
"GET /preferences/omar",115,380,570,670,750,880,970,1000,1200,1200
"GET /preferences/vladimir",140,420,580,670,730,960,1100,1100,1100,1200
"GET /preferences/wayne",117,350,490,620,700,880,1000,1100,1200,1400
"Total",627,390,530,640,700,900,1000,1100,1200,1400
```

The response times there were all over 400ms, and the worst run was 490ms on average.  The new response times average around 250ms (one is 261ms average, the rest are lower).

**Comment by stepanstipl** [comment]
Here is couple of results from our prod runs:
```
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",150,31,36,49,57,77,95,180,190,290
"GET /preferences/nvda",144,32,35,41,48,77,88,100,110,130
"GET /preferences/omar",158,32,38,53,64,85,97,110,130,130
"GET /preferences/vladimir",149,31,36,42,51,81,88,100,120,190
"GET /preferences/wayne",169,31,33,44,58,79,92,100,120,280
"Total",770,31,35,45,56,79,93,110,130,290
```
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/244626141

```
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",151,34,43,61,74,99,120,140,200,290
"GET /preferences/nvda",134,35,39,45,53,77,100,130,140,200
"GET /preferences/omar",145,33,42,57,71,92,120,140,190,240
"GET /preferences/vladimir",155,34,40,65,80,99,130,200,250,290
"GET /preferences/wayne",168,33,40,56,70,91,100,110,120,130
"Total",753,34,41,55,70,95,110,140,200,290
```
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/243765837

And also 2 latest from CI dev (as dev envs are a bit smaller):
```
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",156,36,42,54,69,96,110,130,300,300
"GET /preferences/nvda",161,37,46,63,71,97,100,150,200,280
"GET /preferences/omar",157,34,38,42,47,82,100,110,130,130
"GET /preferences/vladimir",167,36,46,64,77,91,100,130,190,200
"GET /preferences/wayne",143,38,46,66,76,94,100,120,140,140
"Total",784,36,44,57,71,93,100,130,150,300
```
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/243765818

```
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",166,36,42,57,63,98,100,160,190,200
"GET /preferences/nvda",160,38,45,56,66,86,100,110,120,170
"GET /preferences/omar",156,39,47,60,74,97,100,120,140,170
"GET /preferences/vladimir",160,39,47,73,80,98,100,120,140,150
"GET /preferences/wayne",145,37,44,53,67,93,100,130,130,160
"Total",787,38,45,58,70,96,100,130,150,200
```
https://gitlab.com/gpii-ops/gpii-infra/-/jobs/244323417

To me, it seems there's still a major performance difference between the currently deployed and the new versions.  All the current runs are consistent with all responses below `300`, with 99% percentile below `200` and 50%th below `40`.

While the new version is slower -  `1400`, 99% being `850` and 50%th being `180`.

This looks to me like **4-5x** worse response times which is pretty significant difference.

**Comment by stepanstipl** [comment]
I've tried to do a little graph (showing 50th, 99th & 100th percentile values), perhaps it's more obvious visually:
pr-438

(it's just a simple sheet - if anyone's interested you should be able to see it - https://drive.google.com/file/d/1oCBucuH5ThRHGoBucbY50zr2VsMkp_d8/view?usp=sharing)

**Comment by amatas** [comment]
Thanks you @stepanstipl and @the-t-in-rtf , I would like to know what the core team thinks about the implications of merging this change.

If they are fine with this new time responses, I guess that we would need to increase the threshold of the tests of the pipeline, otherwise we could not promote to prd.

**Comment by the-t-in-rtf** [comment]
At the moment, the first request pays a fairly significant performance penalty to transform and compile the original schema, which is then cached..  In our case, we pay this penalty once per preferences server instance, so we may have a couple of fairly slow outliers that we can take care of.

While I was working on the original fix, I put in wiring that could be used by downstream components to cache their schemas as part of their startup.  I plan to try this out with a branch of universal and see whether it helps.

**Comment by stepanstipl** [comment]
> so we may have a couple of fairly slow outliers that we can take care of

@the-t-in-rtf that is interesting and unfortunately I'm not familiar enough with the details, but I would expect that outliers should not affect metrics like the 50th percentile, which also seems to be consistently slower.

I also remember there was some work done on "pre-warming" indices - to avoid slow first response issue, but that was CouchDB problem - https://github.com/GPII/universal/blob/ee4486b17573f8476f705ca327754d0fa049098f/scripts/deleteAndLoadSnapsets.sh#L15-L23

**Comment by stepanstipl** [comment]
Here is a Stackdriver graph for prod for last 6 weeks:
pref-prd

So we do have occasional outliers shown in the 100th percentile, but 99th seems to be consistently below 200.

I've also shared graphs from other envs, this should be publicly viewable:
- PRD - https://public.google.stackdriver.com/public/chart/9897918960576351850?drawMode=color&showLegend=true&theme=light&timeframe=6w
- STG - https://public.google.stackdriver.com/public/chart/5165315230945070190?drawMode=color&showLegend=true&theme=light&timeframe=6w
- CI DEV - https://public.google.stackdriver.com/public/chart/6547386829499240350?drawMode=color&showLegend=true&theme=light&timeframe=6w

The pattern seems to be same for all - sometimes outlier, 99th consistently below 200.

**Comment by the-t-in-rtf** [comment]
The outlier is almost certainly the first pass on each node, which doesn't benefit from the global validation cache.  I am testing that and another key improvement on my dev cluster now.

**Comment by the-t-in-rtf** [comment]
Sorry, I mean I expect there to consistently be one in staging with my previous performance fix.

**Comment by the-t-in-rtf** [comment]
OK, here are the latest numbers from my dev cloud:

```
"avg_response_time": 111.77585846338516,
// ...
null_resource.locust_swarm_session (local-exec): Stats distribution:
null_resource.locust_swarm_session (local-exec): "Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
null_resource.locust_swarm_session (local-exec): "GET /preferences/carla",195,93,110,130,140,170,210,290,520,640
null_resource.locust_swarm_session (local-exec): "GET /preferences/nvda",199,87,110,130,140,180,230,300,380,550
null_resource.locust_swarm_session (local-exec): "GET /preferences/omar",204,93,110,130,150,190,240,320,420,700
null_resource.locust_swarm_session (local-exec): "GET /preferences/vladimir",220,91,110,130,140,170,230,300,350,430
null_resource.locust_swarm_session (local-exec): "GET /preferences/wayne",180,94,120,140,160,190,260,300,500,560
null_resource.locust_swarm_session (local-exec): "Total",998,91,110,130,150,180,230,300,420,700
```

**Comment by the-t-in-rtf** [comment]
```
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"Current Prod Total",770,31,35,45,56,79,93,110,130,290
"Initial Caching Fix Total",627,390,530,640,700,900,1000,1100,1200,1400
"New Fixes Total",998,91,110,130,150,180,230,300,420,700`
```

So, still slower, but much improved.

**Comment by stepanstipl** [comment]
thanks @the-t-in-rtf - below is just pretty much what we discussed in a chat just for other's benefit:

_**Note about dev environments:**_ these are slightly different compared to prd - smaller instance sizes, only 2 instances of CouchDB and preferences (instead of current 3 in prod), but as you can see on the graphs above and the Stackdriver graphs the difference tends to be within 10-20% max (in both directions), so imho results from dev & prod are comparable

Now to the performance - it's definitely better 👍, thanks! At a first sight it looks we’re now somewhere around 3x of the current response times. So better, yet we’re talking still about **300%** of the original times.

And obviously you need a context here as in what are the new changes implemented, but this would not be sustainable over long-term run.

If you have a request that takes `1s`, after the change like this we would be on `3s`, and imagine you have another change with similar `3x` performance hit, you would now be talking about the original request now taking `9s`.

We should be careful about this as at this rate we’ would be pretty much looking at an exponential increase over time.

**Comment by amatas** [comment]
This is supposed to be merged today, but we prefer to wait due the performance penalty until either the performance is going back to the previous ratio or all the team is aware of this change and agrees with the merge (It will be exposed in the next architecture meeting).

**Comment by stepanstipl** [comment]
@the-t-in-rtf I just resolved some conflicts (testing smth).

Can we close this PR for now (and create a new one or reopen once we're ready)?

**Comment by the-t-in-rtf** [comment]
@stepanstipl, yes, that's fine, I'll put in a new pull when I'm ready.

**Pull request closed without merging**
