### PR TITLE
GPII-3715: Move Audit Logging Config to  native Terraform

### PR DESCRIPTION
**Pull request by stepanstipl**
This is required as part of migration to new v2.0.0 version of Terraform Google Provider, as the google_project_iam_policy resource became strictly authoritative on the complete `policy_data` object (see https://www.terraform.io/docs/providers/google/version_2_upgrade.html#resource google_project_iam_policy for details). Since TF supports managing Audit Logging config natively now, it only makes sense to use TF to do this.

Also, instead of having to list individually all the services, GCP Resource Manager API supports special value `allServices` (see `https://cloud.google.com/resource manager/reference/rest/Shared.Types/AuditConfig for details). This has an additional benefit as it will automatically stay up-to-date as Google releases support for Audit Logs for additional services (see https://cloud.google.com/logging/docs/audit/#services for details).

This has been tested and should go together with https://github.com/gpii-ops/exekube/pull/43

### CODE REVIEW

**Comment by natarajaya** [comment]
LGTM

**Comment by mrtyler** [comment]
LGTM

auditConfigs clean-up looks nice :). Do we have anything to test after that change to make sure we're still getting all the audit logs we want?

**Comment by stepanstipl** [comment]
I did verify manually on the test org, will do same for prod. Command to get actual policy is: `gcloud projects get-iam-policy <project_id>`.

Also reading actual data access logs (those are interesting as those are optional compared to admin access) can be done with:
```
gcloud logging read \                                                                                                                 (move-to-istio|✚10…) 0
    'logName="projects/gpii-gcp-prd/logs/cloudaudit.googleapis.com%2Fdata_access"' \
    --limit 5 \
    --freshness 1d --project gpii-gcp-prd --format="table(timestamp, resource.labels)"
TIMESTAMP                       LABELS
2019-02-20T11:21:13.203708976Z  {u'project_id': u'gpii-gcp-prd', u'method': u'google.monitoring.v3.MetricService.ListMetricDescriptors', u'service': u'monitoring.googleapis.com'}
2019-02-20T11:21:11.913614764Z  {u'cluster_name': u'k8s-cluster', u'nodepool_name': u'', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T11:21:09.941037Z     {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T11:21:09.795038Z     {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T11:21:09.222622Z     {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
```

Command above shows output for prod before merge -> logs are comming. I'll update this ticket after this changes is deployed to confirm.

**Comment by stepanstipl** [comment]
After deploy:
```
$ gcloud projects get-iam-policy gpii-gcp-prd

...
auditConfigs:
- auditLogConfigs:
  - logType: DATA_WRITE
  - logType: DATA_READ
  - logType: ADMIN_READ
  service: allServices
...
```
^ This looks as expected, Audit logs enabled for all svcs.

```
$ gcloud logging read \
    'logName="projects/gpii-gcp-prd/logs/cloudaudit.googleapis.com%2Fdata_access"' \
    --limit 5 \
    --freshness 1d --project gpii-gcp-prd --format="table(timestamp, resource.labels)"
TIMESTAMP                    LABELS
2019-02-20T14:25:25.791Z     {u'instance_id': u'', u'project_id': u'gpii-gcp-prd', u'zone': u'us-central1-b'}
2019-02-20T14:25:25.739483Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:25.672401Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:25.647419Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:25.645Z     {u'instance_id': u'', u'project_id': u'gpii-gcp-prd', u'zone': u'us-central1-f'}

$ date
Wed 20 Feb 2019 15:25:41 CET

$ gcloud logging read \
    'logName="projects/gpii-gcp-prd/logs/cloudaudit.googleapis.com%2Fdata_access"' \
    --limit 5 \
    --freshness 1d --project gpii-gcp-prd --format="table(timestamp, resource.labels)"
TIMESTAMP                    LABELS
2019-02-20T14:25:47.879Z     {u'project_id': u'gpii-gcp-prd', u'location': u'global', u'backend_service_id': u''}
2019-02-20T14:25:43.827275Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:43.824331Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:43.792330Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
2019-02-20T14:25:43.784025Z  {u'cluster_name': u'k8s-cluster', u'project_id': u'gpii-gcp-prd', u'location': u'us-central1'}
```
^ Data access Aufit logs are arriving (note `date` is in CET -> 1h off).

**Pull request merged**
