### PR TITLE
[GPII-3194]: Add us-central1-b, us-central1-c into additional_zones of gke-cluster module

### PR DESCRIPTION
**Pull request by natarajaya**

### CODE REVIEW

**Comment by stepanstipl** [comment]
Looks good. I would consider using exclusively `node_pool` to manage GKE nodes. Also this increases the number of nodes from 2 to 3.

**Comment by mrtyler** [comment]
LGTM

**Comment by mrtyler** [comment]
>  I would consider using exclusively node_pool to manage GKE nodes.

In case anyone else had to look this up:
* https://cloud.google.com/kubernetes-engine/docs/concepts/node-pools
* https://www.terraform.io/docs/providers/google/r/container_cluster.html
* https://www.terraform.io/docs/providers/google/r/container_node_pool.html

@stepanstipl, it looks like specifying `node_pool` would give us more flexibility but I'm not sure what value it adds right now? It looks like the Nodes to end up in a Node Pool now, but it's the default pool instead of a custom pool. What am I missing?

**Comment by natarajaya** [comment]
@mrtyler @stepanstipl Thanks for reviews!

I am going to merge this as it is.

Using node pools can give us more flexibility and better control over cluster nodes in case we, let's say, want different instance flavors in different zones, but I agree with Tyler that it probably does not add any value right now. It will also require changes to `gke-cluster` exekube module.

**Pull request merged**
