### PR TITLE
[GPII-4068]: Improve CouchDB rollouts with Istio's retry policy, lifecycle hooks

### PR DESCRIPTION
**Pull request by natarajaya**
This PR:
* Adds `preStop` lifecycle hook to CouchDB stateful set that enables maintenance mode for the node (to fail readiness check and stop the flow of traffic from load balancer, and also stop direct node-to-node communication via headless service) and gives it some time to finish handling existing connections.
* Adds Istio's `VirtualService` to control the ingress traffic on CouchDB ClusterIP service. Currently it only adds 2 second timeout for all ingress requests and does not change number of tries. However, this may also lead to situations when request times out, but data was actually written to DB, this should be handled on client side.

According to my tests, these changes reduce failure rate from from 5-15 failures per 5k requests (`POST /access_token`) made during stateful set restart, to 0-1 failures (caused by `VirtualService` timeout). In case timeout is not set, instead of failures, we'll see requests that take 5-30 seconds to complete.

### CODE REVIEW

**Comment by natarajaya** [comment]
Updated PR title and description to reflect current state of things.

**Comment by stepanstipl** [comment]
Looks good. Good job on the health checks!

I'm not quite sure about introducing the timeout. What are the benefits?

What if the real requests take more than 2s? I think we have queries like that, for example, data loader or those updates we were running as part of the previous release.

**Comment by natarajaya** [comment]
Thanks for the reviews!

> I'm not quite sure about introducing the timeout. What are the benefits?

@stepanstipl I am also not sure :) Main benefit is that instead of requests that take dozens of seconds, but succeed at the end (`Looks like max_response_time (120162) is worse than desired (1500)!`), we'll have requests that fail after spending 2 seconds waiting for CouchDB. IMO, from end-user perspective, this is more desirable.

> What if the real requests take more than 2s

Again IMO, 2 seconds is a reasonable period of time for NoSQL DB to produce a response in any day-to-day circumstances. In case regular requests take more time to complete – something needs to be changed (i.e. requests optimized, CouchDB scaled up, etc.)

> or at least with higher timeout time.

@amatas How about I set it to 10 seconds to have some extra buffer for unpredicted behaviors (slow requests from dataloader or flushtokens)?

**Comment by amatas** [comment]
> @amatas How about I set it to 10 seconds to have some extra buffer for unpredicted behaviors (slow requests from dataloader or flushtokens)?

sounds good to me

**Comment by stepanstipl** [comment]
Thanks @natarajaya. As @amatas , I would also prefer to leave it to disable now, and eventually introduce it later if we need it.

Probably higher timeout (like 10s) would be ok, but we should base this on reviewing the actual queries, incl. the ones that I remember can take long time -  cleaning expired tokens, migration work like the one in last release, views being queried for the first time... etc.

Also introducing artificial timeouts like this can be tricky, and can lead to overloading your application if not done properly (this usually includes coordinating timeouts & retries across the stack and concepts like circuit breakers).

**Comment by natarajaya** [comment]
Ok, agree that timeouts and retries is a tricky topic, so let's leave it aside for now.

**Pull request merged**
