### PR TITLE
GPII-3324 Stackdriver logs export

### PR DESCRIPTION
**Pull request by mrtyler**
Continuation of https://github.com/gpii-ops/gpii-infra/pull/146, which was accidentally closed by Github and/or me (somehow).

I rebased onto current master, but kept the commits the same. The first four are the same as they were in #146. Subsequent commits (starting with e51176c)  are new work.

### CODE REVIEW

**Comment by mrtyler** [comment]
Now I'll add some new commits.

**Comment by stepanstipl** [comment]
+1 on the variables for classes, looks good - I'm not sure where exactly I ended reviewing last time ;).

Have we tested this with the new Stackdriver beta names?

**Comment by mrtyler** [comment]
> Have we tested this with the new Stackdriver beta names?

Yes.

**Comment by stepanstipl** [comment]
@mrtyler I've updated the PR title to `Stackdriver logs export` from bare `export`, I hope you don't mind (I just opened this PR for the 3rd time in a row as I wasn't sure what it's about)

**Comment by stepanstipl** [comment]
LGTM

**Comment by amatas** [comment]
LGTM

**Pull request merged**
