### PR TITLE
GPII-4243: Deploy performant lower memory validation and remove context manager.

### PR DESCRIPTION
**Pull request by the-t-in-rtf**
See [GPII-4243](https://issues.gpii.net/browse/GPII-4243) for details.

### CODE REVIEW

**Comment by the-t-in-rtf** [comment]
We'd like to deploy to staging on Monday the 25th (it's in the ticket, but I thought I'd also mention here for clarity).

**Comment by stepanstipl** [comment]
The PR looks good. Can you attach some test results from dev demonstrating that the performance problem that failed the previous PR (https://github.com/gpii-ops/gpii-infra/pull/438) has been resolved?

**Comment by natarajaya** [comment]
Thanks @the-t-in-rtf, LGTM!
Stepan is raising good question about performance issues.

**Comment by the-t-in-rtf** [comment]
Here are a few recent sample runs of the preferences "read" tests on my dev cloud:

```
Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",194,57,66,78,87,110,120,150,160,250
"GET /preferences/nvda",206,61,72,81,90,110,140,170,200,200
"GET /preferences/omar",215,62,78,85,92,110,150,180,200,270
"GET /preferences/vladimir",199,56,65,78,86,100,130,160,200,200
"GET /preferences/wayne",191,55,66,77,89,100,130,150,180,300
"Total",1005,58,70,82,89,110,130,160,200,300
--
Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",217,56,63,74,78,94,100,120,130,170
"GET /preferences/nvda",210,57,65,71,78,93,110,130,160,190
"GET /preferences/omar",187,58,72,82,91,100,120,160,190,200
"GET /preferences/vladimir",175,55,61,70,74,87,120,170,200,240
"GET /preferences/wayne",222,51,60,69,76,90,100,130,150,170
"Total",1011,55,64,73,78,94,110,130,160,240
--
Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",188,58,76,86,94,100,120,160,180,220
"GET /preferences/nvda",193,58,70,79,88,100,120,150,150,180
"GET /preferences/omar",219,58,66,76,82,100,120,160,180,280
"GET /preferences/vladimir",202,57,69,76,80,92,110,130,140,160
"GET /preferences/wayne",211,53,65,75,82,100,120,150,160,210
"Total",1013,57,70,78,84,100,120,150,160,280
--
Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"GET /preferences/carla",181,62,73,86,96,110,170,250,280,380
"GET /preferences/nvda",208,66,82,95,98,130,160,170,190,480
"GET /preferences/omar",211,59,71,80,88,99,140,180,190,220
"GET /preferences/vladimir",204,63,77,87,99,130,150,250,300,430
"GET /preferences/wayne",205,60,72,84,90,100,120,150,180,310
"Total",1009,62,74,87,94,120,150,190,250,480
```

The last one is slightly slower [than we'd usually like](https://raisingthefloor.slack.com/archives/C9PCPPUF8/p1573644351105200), but I think it's somewhat skewed by my methodology, where I run a bunch of smoke tests back to back.  Although we don't have much to compare them with, I'll post the write results in a few.

**Comment by the-t-in-rtf** [comment]
Here are the write results:

```
tats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"PUT 1. PUT valid prefs with a GPII key.",128,290,330,380,400,460,490,520,580,790
"GET 2. GET the prefs we just PUT.",126,97,110,140,140,160,180,210,270,360
"POST 3. POST valid prefs without a GPII key.",126,180,210,240,250,300,330,420,460,510
"GET 4. GET the prefs we just POSTed.",124,90,110,130,140,180,210,220,310,370
"Total",504,150,200,240,270,330,400,480,510,790
--

Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"PUT 1. PUT valid prefs with a GPII key.",128,280,310,370,380,510,700,1200,1200,1200
"GET 2. GET the prefs we just PUT.",127,86,120,140,160,190,240,320,390,400
"POST 3. POST valid prefs without a GPII key.",124,170,230,280,290,390,430,760,920,1100
"GET 4. GET the prefs we just POSTed.",124,98,120,140,150,200,240,280,630,1200
"Total",503,160,210,250,280,370,450,700,920,1200
--

Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"PUT 1. PUT valid prefs with a GPII key.",127,310,360,400,420,460,540,590,640,680
"GET 2. GET the prefs we just PUT.",126,100,110,130,140,170,190,240,260,270
"POST 3. POST valid prefs without a GPII key.",126,190,230,270,280,330,390,490,490,540
"GET 4. GET the prefs we just POSTed.",126,97,130,150,180,210,220,290,300,370
"Total",505,170,210,260,290,370,430,490,540,680
--

Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"PUT 1. PUT valid prefs with a GPII key.",127,340,400,430,450,490,590,640,640,650
"GET 2. GET the prefs we just PUT.",122,110,130,150,170,190,220,270,280,310
"POST 3. POST valid prefs without a GPII key.",121,190,240,270,280,350,390,470,480,510
"GET 4. GET the prefs we just POSTed.",121,100,130,150,150,190,220,330,510,780
"Total",491,170,220,260,300,400,470,540,620,780
--

Stats distribution:
"Name","# requests","50%","66%","75%","80%","90%","95%","98%","99%","100%"
"PUT 1. PUT valid prefs with a GPII key.",126,300,340,390,410,500,570,750,770,770
"GET 2. GET the prefs we just PUT.",124,94,110,130,150,180,200,210,230,300
"POST 3. POST valid prefs without a GPII key.",124,190,210,230,260,300,360,400,410,420
"GET 4. GET the prefs we just POSTed.",121,96,110,130,130,160,200,220,220,550
"Total",495,160,200,230,280,340,420,530,640,770
```

For comparison, see [the discussion in the pull that added the prefs write tests](https://github.com/gpii-ops/gpii-infra/pull/518#issuecomment-544868706).  Those were much worse response times, which makes sense given the point of this pull.

**Pull request merged**
