### PR TITLE
GPII-3450: Accommodate the new usage of GPII_FLOWMANAGER_TO_PREFERENCESSERVER_URL

### PR DESCRIPTION
**Pull request by cindyli**
This pull request needs to be merged once the universal pull request https://github.com/GPII/universal/pull/699 makes into the master so that the deployment to the production and staging environments continues to function.

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

**Comment by natarajaya** [comment]
LGTM

**Comment by amatas** [comment]
LGTM

**Comment by stepanstipl** [comment]
👍

**Comment by cindyli** [comment]
Yes, this PR should be merged. The change in this PR is to set the URL to the preferences server that the cloud based flow manager(CBFM) can retrieve preferences from. I believe things still seem to be working without this PR is because [the flow manager test|https://github.com/gpii-ops/gpii-infra/blob/master/aws/rakefiles/deploy.rake#L30] is testing /access_token endpoint where CBFM directly talks to CouchDB without contacting the preferences server. The endpoints that involve the workflow of "CBFM -> preferences server -> couchDB" are:
* /ready
* GET /settings
* PUT /settings

As we talked in the slack, `https://flowmanager.prd.gpii.net/ready` endpoint currently returns the error `Cannot connect to Preferences Server at http://preferences.gpii.svc.cluster.local/preferences/%gpiiKey?merge=%merge`. 

I manually tested`GET /settings` endpoint which still works. I believe this is because without this PR, the current `preferences_url` value in the master provides the full URL to the get/set endpoints on the prefs server. The server http request processor is smart enough to discard the further url concatenation performed by the code. When this PR is merged, the url concatenation performed in the code will take effect.

**Pull request merged**
