### PR TITLE
[GPII-2805]: Update CouchDB restoration guide

### PR DESCRIPTION
**Pull request by natarajaya**
Included all fixes post today's test.

[Rendered README.](https://github.com/natarajaya/gpii-infra/blob/GPII-2805-2/gcp/README.md#data-corruption-on-all-replicas-of-couchdb-cluster)

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

**Comment by stepanstipl** [comment]
lgtm

**Comment by stepanstipl** [comment]
Currently following the guide & running tests will break CI because of encryption issues (more in pad & I'll add a ticket link once created).

**Comment by natarajaya** [comment]
@stepanstipl Locust issue has nothing to do with this guide and needs to be fixed separately:
https://issues.gpii.net/browse/GPII-4003

**Comment by stepanstipl** [comment]
> @stepanstipl Locust issue has nothing to do with this guide and needs to be fixed separately:
https://issues.gpii.net/browse/GPII-4003

@natarajaya while I agree this should be fixed elsewhere, I also don't think that having a guide that breaks your system is ok.

Adding an additional step to destroy the locust module & state to the restoration guide would prevent this issue happening until it's properly fixed.

**Comment by natarajaya** [comment]
@stepanstipl Locust issue is being addressed in #437, I am pretty sure it'll get merged before anybody needs to use this guide again.

**Pull request merged**
