### PR TITLE
[GPII-3299]: Clean old SA keys after creating new one

### PR DESCRIPTION
**Pull request by natarajaya**

### CODE REVIEW

**Comment by mrtyler** [comment]
The code looks good.

I think running this every time `:configure_serviceaccount` runs is a bit too aggressive. Someone takes a look at `dev-gitlab-runner` and CI's Keys are invalidated.

How about instead calling this logic as part of `:destroy`?

Also, can you create a task for this, maybe `:clean_keys`? Then it will be available for ad-hoc use as well -- add some documentation, "if you get this error message, run this task"?

**Comment by stepanstipl** [comment]
Agree that running this every time sounds a bit dangerous. Is there never a use case when we would need more than one key?

**Comment by natarajaya** [comment]
@mrtyler @stepanstipl Thanks for your valuable reviews!
Arguments about CI key invalidation due to developer debugging `dev-gitlab-runner` project sounds reasonable.
I moved the code to a separate `:destroy_sa_keys` task, updated README.
Instead of making this a part of `:destroy` (which would again invalidate CI keys in case developer needs to run `:destroy` for CI infra on his machine), I added this as an additional CI step before `rake clobber`.

**Comment by mrtyler** [comment]
I think calling :destroy_sa_keys from gitlab-ci.yml is a good solution. Do you think we should add the call to gcp-stg and gcp-prd in addition to gcp-dev?

**Comment by mrtyler** [comment]
LGTM

**Pull request merged**
