### PR TITLE
GPII-3339: Disable Kubernetes Dashboard

### PR DESCRIPTION
**Pull request by stepanstipl**
Kubernetes Dashboad has been deprecated on GKE (see
https://cloud.google.com/kubernetes-engine/docs/concepts/dashboards for
details). This disables Kube Dashboard and removes other related bits of
code that are no longer needed.

This depends on gpii-ops/exekube#14, which needs to be merged first.

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

administration-tasks comes from a sample exekube project, so I wonder about deleting the dashboard configuration entirely vs disabling it. However, given that Kubernetes Dashboard is deprecated for GKE and that we have no meaningful migration path for changes from the upstream sample exekube project's administration-tasks to our administration-tasks, deleting is probably best.

**Comment by stepanstipl** [comment]
Thanks @mrtyler. One more thing to mention and which I've forgotten to add to the description - after applying this, one needs to delete `terragrunt` docker volume, otherwise the run will fail. This should be ok for CI, as the volumes get deleted after each run, but was causing me trouble on my local machine as I usually just run `rake`. Not sure if this should be mentioned anywhere, as it's a one-time thing.

**Comment by amatas** [comment]
LGTM, just throw a heads up in our channel when this PR is merged in order to delete our docker volumes

**Comment by stepanstipl** [comment]
Thanks, +1 for removing `administration-tasks`, that is actually the module that's causing the issue mentioned above, and also it has chart directly underneath it, instead of in `common/charts`. I've created a ticket GPII-3392 to look into this.

**Pull request merged**
