### PR TITLE
[GPII-3418]: Tune resource requests one more time

### PR DESCRIPTION
**Pull request by natarajaya**
This is the long-term solution I promised.

For dev clusters I had to keep requests lowered in order to stay on cheaper `n1-standard-2` nodes.

For staging / prod clusters:
* To have "more predictable" scheduling with requests = limits
* To also have more replicas of preferences, flowmanager and couchdb (similarly to AWS setup)
* And finally, to have enough room for rolling updates with `maxUnavailable: 0`

I suggest to use `n1-highcpu-4` instances. They are a bit cheaper than `n1-standard-4` and have significantly less RAM (4GB vs 15GB), but since we are very far away from hitting RAM limit, it seems like the most optimal choice in our situation.

Changing node type will most likely cause Terraform to attempt to recreate the cluster. I am not sure if there is a way around this issue for staging and prod, I am open to suggestions!

Using container_node_pool should improve this situation:
https://issues.gpii.net/browse/GPII-3419

### CODE REVIEW

**Comment by amatas** [comment]
LGTM

**Comment by mrtyler** [comment]
> value passed down as a parameter from each environment

+1

**Comment by natarajaya** [comment]
@stepanstipl @mrtyler Good point! Unfortunately, getting rid of env-based interpolations in modules requires adding more plumbing in order to pass variables from Terragrunt to Terraform and then into templates. But I also believe that it results in a bit more clear module code and more flexible per-environment configs.

Please review updated version!

**Comment by mrtyler** [comment]
LGTM

Thanks for re-plumbing those templated variables. I think the new form is easier to understand and more consistent with the Exekube/Terraform module model.

**Pull request merged**
