### PR TITLE
GPII-3384: Update readme and remove common/versions.yml

### PR DESCRIPTION
**Pull request by stepanstipl**
- Updates `aws/README.md` to reflect the current state of things.
- Removes `common/versions.yml` which has been moved to shared dir

### CODE REVIEW

**Comment by amatas** [comment]
Wouldn't it be better if the `versions.yml` file is moved to `shared/versions.yml` overwriting the old one?

**Comment by amatas** [comment]
LGTM, just the concern about leave behind the latest version of the universal containers

**Comment by mrtyler** [comment]
LGTM

**Comment by natarajaya** [comment]
LGTM

**Comment by stepanstipl** [comment]
@amatas as of now the 2 files are identical, so there shouldn't be any danger of leaving behind old version. Also the file in `shared/` "should" 😉  be the only one that gets updated - that's why I didn't touch that, as doing anything here could only cause potential conflict if the updater would update it in the meantime

thanks for review everyone

**Pull request merged**
