### PR TITLE
GPII-3327: Update to Beta Stackdriver names.

### PR DESCRIPTION
**Pull request by mrtyler**
In my excitement to merge #114, I forgot to do this update that @natarajaya  told me I would need.

### CODE REVIEW

**Comment by natarajaya** [comment]
LGTM

**Comment by stepanstipl** [comment]
Looks good, has this been actually tested in the updated form?

**Comment by amatas** [comment]
LGTM

**Comment by mrtyler** [comment]
> has this been actually tested in the updated form?

Of course.

**Pull request merged**
