### PR TITLE
GPII-3492: Start section on operational principles.

### PR DESCRIPTION
**Pull request by mrtyler**
Per our Parking Lot discussion, I established a section in the README for recording this kind of thing.

### CODE REVIEW

**Comment by natarajaya** [comment]
LGTM

**Comment by amatas** [comment]
LGTM, I would add as well "Avoid to deploy on Friday or in the day previous of a festivity"

**Comment by stepanstipl** [comment]
lgtm

**Comment by mrtyler** [comment]
Added a note about Fridays and holidays, per Alfredo.

**Pull request merged**
