### PR TITLE
GPII-3916 - Fix Backup exporter alert definitions

### PR DESCRIPTION
**Pull request by amatas**
Second attempt to fix the "always update" issue when the monitoring is deployed in stg and prd. This time I've saved the JSON definition directly from Stackdriver.

`rake deploy_module["k8s/stackdriver/monitoring"]` output:
```
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Pod `couchdb-prometheus-exporter` exports a metric" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "IAM audit logs do not contain policy modification events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Snapshots are being created for persistent volumes of CouchDB stateful set" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Stackdriver audit log does not contain alert policy modification events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Backup-exporter process reports one or more errors" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "GKE audit log does not contain cluster creation events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "CloudDNS audit log does not contain zone modification events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Uptime check on `flowmanager.alfredo.dev.gcp.gpii.net` is green" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "GCE audit log does not contain firewall modification events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "GCE audit log does not contain non-GKE instance creation events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s cluster allocatable resource utilization stays within 85% of capacity" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Service management log does not contain API enabling / disabling events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s-snapshots logs do not contain errors" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s cluster API logs do not contain `kubectl exec` events" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "Backup-exporter snapshots are missing for more than 12 hours" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s pods utilize less than 85% of persistent volume capacity" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s containers does not restart more often than 1.5 times per minute" is up-to-date...
null_resource.apply_stackdriver_monitoring (local-exec): Alert policy "K8s container CPU utilization stays within 85% of limit" is up-to-date...

```

### CODE REVIEW

**Comment by mrtyler** [comment]
LGTM

IIRC this is your third attempt to fix the alerting policy. Is there some documentation that should be updated to help alert authors get the configuration right on the first try?

**Comment by natarajaya** [comment]
@amatas Since you are dealing with this, can you please update display names for backup exporter policies that you added in common and gcp parts? The policy name should describe its "green" state, i.e. "Backup-exporter process does not report errors" instead of "Backup-exporter process reports one or more errors". And condition name should describe "red" state, because this is what we see in email and slack alerts. Check the [pod_exec](https://github.com/gpii-ops/gpii-infra/blob/master/gcp/modules/gcp-stackdriver-monitoring/resources/alert_policies/pod_exec.json) policy for example.

**Comment by amatas** [comment]
done @natarajaya

**Comment by natarajaya** [comment]
@amatas Thanks! Can you update ones in [common part](https://github.com/gpii-ops/gpii-infra/tree/master/common/modules/gcp-stackdriver-monitoring/resources/alert_policies) as well?

**Comment by amatas** [comment]
@mrtyler  no extra doc needed. I used these instructions and perhaps a couple of more lines to write the json file to disk and then copy it to the resources directory:
https://github.com/gpii-ops/gpii-infra/tree/master/gcp#to-add-new-resource--debug-existing-resources

**Comment by amatas** [comment]
> @amatas Thanks! Can you update ones in [common part](https://github.com/gpii-ops/gpii-infra/tree/master/common/modules/gcp-stackdriver-monitoring/resources/alert_policies) as well?

done

**Comment by natarajaya** [comment]
LGTM!

**Pull request merged**
