### PR TITLE
GPII-3641 GPII-3856 GPII-3857 Image updates

### PR DESCRIPTION
**Pull request by mrtyler**
This PR replaces #370 -- there is nothing new to review. It has the contents of #370, rebased onto master now that #367 and #368 (and version-updater companion PRs) are merged, minus #372 (which was merged separately while merging #367 and #368).

* GPII-3641: Replace busybox with alpine for couchdb init container
* ~GPII-3871: Re-run port-forward each time when checking membership for couchdb.finish_cluster~ --> #377 
* GPII-3856 Update couchdb-prometheus-exporter's prometheus-to-sd to the latest, 0.5.1
* GPII-3857: Update nginx-ingress to the latest 0.21.1 and (for fun) update the chart with latest from upstream.
* ~GPII-3846: Update couchdb to 2.3.0 and (for fun) couchdb-statefulset-assembler to 1.2.0.~ --> #376 

Additional testing info:

- [x] Deploy dev env with current master (un-updated images/charts -- in particular couchdb 2.2.0).
   * This deploy and all deploys happen with `execute_destroy_pvcs = "false"` and `execute_recover_pvcs = "true"`, to simulate a long-lived env
- [x] Add [custom data](https://github.com/gpii-ops/gpii-infra/blob/master/gcp/README.md#hack-adding-data-to-couchdb) to couchdb.
- [x]  Switch to this PR (updated images/charts -- in particular couchdb 2.3.0) and deploy.
- [x] (For fun, run test_flowmanager during deploy)
- [x] Verify custom data still present in couchdb.
- [x] Watch couchdb logs for any indication of trouble related to the new version.
- [x] Switch back to current master and downgrade images (back to couchdb 2.2.0).
- [x] Verify custom data still present in couchdb.
- [x] Watch couchdb logs for any indication of trouble related to the new version.
   * Downgrade appears to fail:
```
[info] 2019-04-25T03:24:53.087604Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.210.0> -------- db _nodes died with reason {invalid_header_size,{db_header,7,2,0,{8460,{2,0,{size_info,90,8}},165},{8625,2,167},{16614,[],455},nil,nil,205,1000,<<"be960de869802d865ff4000153916b13">>,[{'couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local',0}],0,1000}}

[info] 2019-04-25T03:24:53.087839Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.210.0> -------- db _users died with reason {invalid_header_size,{db_header,7,1,0,{2363,{1,0,{size_info,2089,5361}},118},{2481,1,115},{20917,[],817},nil,nil,205,1000,<<"b0c7a7cd244e8285af4e3313c7fd8e05">>,[{'couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local',0}],0,1000}}

[error] 2019-04-25T03:24:53.087946Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.249.0> -------- CRASH REPORT Process  (<0.249.0>) with 2 neighbors crashed with reason: {invalid_header_size,{db_header,7,2,0,{8460,{2,0,{size_info,90,8}},165},{8625,2,167},{16614,[],455},nil,nil,205,1000,<<"be960de869802d865ff4000153916b13">>,[{'couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local',0}],0,1000}} at couch_bt_engine_header:upgrade_tuple/1(line:212) <= lists:foldl/3(line:1263) <= couch_bt_engine:init_state/4(line:684) <= couch_bt_engine:init/2(line:148) <= couch_db_engine:init/3(line:648) <= couch_db_updater:init/1(line:32) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_db_updater,init,['Argument__1']}, ancestors: [<0.248.0>], messages: [], links: [<0.248.0>,<0.252.0>], dictionary: [{idle_limit,61000},{io_priority,{db_update,<<"_nodes">>}}], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 572

[error] 2019-04-25T03:24:53.088543Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.251.0> -------- CRASH REPORT Process  (<0.251.0>) with 2 neighbors crashed with reason: {invalid_header_size,{db_header,7,1,0,{2363,{1,0,{size_info,2089,5361}},118},{2481,1,115},{20917,[],817},nil,nil,205,1000,<<"b0c7a7cd244e8285af4e3313c7fd8e05">>,[{'couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local',0}],0,1000}} at couch_bt_engine_header:upgrade_tuple/1(line:212) <= lists:foldl/3(line:1263) <= couch_bt_engine:init_state/4(line:684) <= couch_bt_engine:init/2(line:148) <= couch_db_engine:init/3(line:648) <= couch_db_updater:init/1(line:32) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_db_updater,init,['Argument__1']}, ancestors: [<0.250.0>], messages: [], links: [<0.250.0>,<0.253.0>], dictionary: [{idle_limit,61000},{io_priority,{db_update,<<"_users">>}}], trap_exit: false, status: running, heap_size: 987, stack_size: 27, reductions: 543

[error] 2019-04-25T03:24:53.090499Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.255.0> -------- Could not open file ./data/_users.couch: file already exists

[info] 2019-04-25T03:24:53.090569Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.210.0> -------- open_result error file_exists for _users

[error] 2019-04-25T03:24:53.090938Z couchdb@couchdb-couchdb-1.couchdb-couchdb.gpii.svc.cluster.local <0.245.0> -------- CRASH REPORT Process  (<0.245.0>) with 1 neighbors exited with reason: no match of right hand value file_exists at couch_auth_cache:ensure_users_db_exists/2(line:447) <= couch_auth_cache:open_auth_db/0(line:419) <= couch_auth_cache:reinit_cache/1(line:282) <= couch_auth_cache:init/1(line:164) <= gen_server:init_it/6(line:328) <= proc_lib:init_p_do_apply/3(line:247) at gen_server:init_it/6(line:352) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_auth_cache,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.204.0>], messages: [], links: [<0.214.0>,<0.247.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 341
```
   * Re-upgrading to 2.3.0 heals the cluster

## Deployment plan - prep phase
- [ ] Merge this PR, #376, and #377
- [ ] version-updater picks up the new versions, syncs the images, and re-writes the generated configs
- [ ] Babysit pipeline to stg. Problems with couchdb or nginx-ingress should be obvious, but monitor the logs
- [ ] Ensure couchdb metrics are still being collected: https://app.google.stackdriver.com/dashboards/11824930462768382974?project=gpii-gcp-stg
- [ ] Review `plan-all-prd` output, ensure changes are as expected (couchdb upgrade good, k8s cluster destruction bad)

## Deployment plan - production phase
- [ ] Wait for planned maintenance time
- [ ] Identify the last set of Snapshots from before the upgrade. Note their IDs, as you will need them in case of couchdb rollback.
- [ ] Promote pipeline to prd. Problems with couchdb or nginx-ingress should be obvious, but monitor the logs
- [ ] Ensure couchdb metrics are still being collected: https://app.google.stackdriver.com/dashboards/5252464485969725191?project=gpii-gcp-prd
- [ ] Email the all clear to outage@

## Rollback plan
- [ ] Revert the bad update (this PR or #376 or both -- hopefully not #377)
- [ ] If reverting nginx-ingress, the environment should recover on its own. If it doesn't, the first serious step is probably `rake redeploy_module`.
- [ ] If reverting couchdb, restore from the Snapshots you identified before: https://github.com/gpii-ops/gpii-infra/blob/master/gcp/README.md#data-corruption-on-all-replicas-of-couchdb-cluster

### CODE REVIEW

**Comment by mrtyler** [comment]
Additional testing info:

- [ ] Deploy dev env with current master (un-updated images/charts -- in particular couchdb 2.2.0).
- [ ] Add [custom data](https://github.com/gpii-ops/gpii-infra/blob/master/gcp/README.md#hack-adding-data-to-couchdb) to couchdb.
- [ ]  Switch to this PR (updated images/charts -- in particular couchdb 2.3.0) and deploy.
- [ ] Verify custom data still present in couchdb.
- [ ] Watch couchdb logs for any indication of trouble related to the new version.
- [ ] Switch back to current master and downgrade images (back to couchdb 2.2.0).
- [ ] Verify custom data still present in couchdb.
- [ ] Watch couchdb logs for any indication of trouble related to the new version.

**Comment by natarajaya** [comment]
Thanks for the CouchDB testing plan! LGTM!

**Comment by stepanstipl** [comment]
I'm just concerned about updating both the nginx & CouchDB in one go. Would it make sense to split this in 2 individual changes? The typical reason - big changes are more difficult to revert & debug.

Otherwise lgtm.

**Comment by mrtyler** [comment]
As discussed in standup, I separated the couchdb upgrade into its own PR (#376) so that we can revert that upgrade separately if necessary.

**Comment by mrtyler** [comment]
I extracted the port re-forwarding fix to #377. My experience is that not having that fix because we revert this PR makes couchdb upgrades/downgrades more annoying.

I also added a deployment plan and rollback plan to the PR description.

**Comment by stepanstipl** [comment]
thanks, lgtm

**Comment by amatas** [comment]
The plan and the code looks good to me.

**Comment by mrtyler** [comment]
This work is complete. Everything went smoothly, except that Sergey's recently added nginx stats are not working with v0.5.1. He is investigating that separately.

**Pull request merged**
