### PR TITLE
[GPII-4058]: Fix sensitive data filtering

### PR DESCRIPTION
**Pull request by natarajaya**
This is a regression, introduced in https://github.com/gpii-ops/gpii-infra/pull/420/files#diff-e0a4c9132be9f827cd9f13dc69eaceedR72

String comparisons looks pretty ugly, but so is the way rake task arguments work.

### CODE REVIEW

**Comment by natarajaya** [comment]
Btw, optional output stream merging for `sh_filter` was added in #135 per @stepanstipl request, and I still have doubts that we need it.

**Comment by stepanstipl** [comment]
Thanks for looking into this @natarajaya, LGTM 👍, and sorry as it seemed to be introduced by my change.

I think that as the rake tasks are currently written/used is quite confusing and will bite us back _(it was my change, but 3 people reviewed without noticing the issue -> shouts unclear code to me)_, but that's probably out of scope here, but perhaps something to remember when we discuss the technical debt.

It would be good to fix the underlying problem of not filtering sensitive data in `stderr` stream. Going over the conversation from #135 - there's one thing that I didn't realize then: from a developer's perspective this is highly unexpected. If I enable `preserve_stderr`, I would not expect that sensitive output filtering would suddenly stop working. And I still believe that deliberately merging streams is undesirable, again something non-standard and unexpected. So in long-term IMHO it would be best to remove that `preserve_stderr` option and fix filtering for both streams (without merging them).

**Comment by amatas** [comment]
LGTM

**Comment by mrtyler** [comment]
@stepanstipl 

> 3 people reviewed without noticing the issue -> shouts unclear code to me

This is not the kind of error I expect code review to catch. Code review is not designed to be, and will never be, a replacement for thorough testing.

**Pull request merged**
