### PR TITLE
[GPII-3836]: Enable secrets bucket versioning for stg, prd

### PR DESCRIPTION
**Pull request by natarajaya**
This PR enables secrets bucket versioning for staging and production environments and should be merged after https://github.com/gpii-ops/exekube/pull/70.

Deployment does not require any special treatment.

### CODE REVIEW

**Comment by natarajaya** [comment]
Added work-in-progress label, because I still need to test recovery of a previous version of a secrets file, encrypted with disabled version of KMS key.

**Comment by natarajaya** [comment]
Tests went successful, this is ready to be merged.

**Comment by natarajaya** [comment]
> What is the rationale behind enabling versioning only in stg and prd

@stepanstipl Dev secrets are less valuable, since our universal dev troubleshooting "policy" is to destroy hard and redeploy when things go weird. But at the same time, secrets versioning should not bring too much of extra cost, so I am fine enabling it for all envs for consistency in case team decides so.

**Comment by stepanstipl** [comment]
> secrets versioning should not bring too much of extra cost, so I am fine enabling it for all envs for consistency in case team decides so.

Thanks @natarajaya, I'm in favor of enabling it everywhere for the sake of parity across envs.

**Pull request merged**
