### PR TITLE
GPII-3871: Re-forward port each time.

### PR DESCRIPTION
**Pull request by mrtyler**
Separated from https://github.com/gpii-ops/gpii-infra/pull/373.

### CODE REVIEW

**Comment by stepanstipl** [comment]
There seems to be a lot of `nginx-ingress` changes unrelated to port-forwarding of CouchDB.

**Comment by mrtyler** [comment]
Per standup discussion, I have rebased this branch to remove extraneous commits. (Git will handle them fine during merge, but may have trouble if we need to revert.)

**Comment by stepanstipl** [comment]
lgtm

**Comment by natarajaya** [comment]
LGTM!

**Pull request merged**
