### PR TITLE
[GPII-3425]: Add helm-tls module

### PR DESCRIPTION
**Pull request by natarajaya**
Corresponding exekube PR: https://github.com/gpii-ops/exekube/pull/39.

This solves two problems:
* Inability to fetch TLS assets without affecting the state of the cluster (as described in https://github.com/gpii-ops/gpii-infra/pull/278).
* Inability to deploy / destroy module or simply run destroy without locally present TLS assets (as described in original ticket).

Migration plan:
- [x] Merge this PR and corresponding exekube PR.
- [ ] For *gpii-gcp-stg*: Manually reconstruct TF state for `helm-tls` module using TLS resources from existing `helm-initializer` module. 
- [ ] For *gpii-gcp-stg*: Manually remove TLS resources and dependencies on them from TF state of `helm-initializer` module.
- [ ] Let pipeline pass staging step.
- [ ] Repeat TF state edits for *gpii-gcp-prd*.
- [ ] Promote pipeline into production.

### CODE REVIEW

**Comment by natarajaya** [comment]
Updated PR description with migration plan.

I did not find any good automated way to deal with TF state issues. However, proposed manual migration is pretty straightforward – using my dev infra, I was able to successfully migrate existing TLS resources from `helm-initializer` to `helm-tls` module without any issues for existing Tiller installation and keeping all deployments it is managing intact.

**Comment by stepanstipl** [comment]
Thanks @natarajaya, It looks good in general

I have 2 questions:

- How do we propose to upgrade dev environments? (I guess ops team can do their own, but what about actual devs?)

- Running apply on `helm-tls` module can still modify cluster, I can see at least 2 scenarios when this can happen:
  - Cluster has not been created yet, the certs do not exist -> apply run will create those
  - The certs expired, therefore running apply will renew the certs (I guess this leaves cluster in broken state?)

Any thoughts on that?

**Comment by natarajaya** [comment]
> How do we propose to upgrade dev environments?

@stepanstipl Run `rake destroy` with the code that created the cluster (probably worth saving last commit SHA somewhere? I'll add parking lot item with that), update to latest master, run `rake` again?

I don't think there are many reasons why devs may want to keep their clusters up thru the migration, but in case of that, I would be happy to guide anyone on how to perform those manual edits on TF state.

> Cluster has not been created yet, the certs do not exist -> apply run will create those

This does not really modify the cluster, right? I think it is fine to let `helm-tls` to generate TLS resources, even if there is no infra, they will be picked up later anyway.

> The certs expired, therefore running apply will renew the certs

This worth separate ticket – we currently generate certs with early renewals set to 2 and 1 years for CA and other certs respectively. I don't think anybody ever tested expiration scenario.

**Comment by mrtyler** [comment]
Code and migration plan LGTM!

**Comment by stepanstipl** [comment]
> This does not really modify the cluster, right? I think it is fine to let `helm-tls` to generate TLS resources, even if there is no infra, they will be picked up later anyway.

It will modify state of the "world", imho `plan` should never do that. But I guess that's topic for the introducing "plan" stage PR.

> The certs expired, therefore running apply will renew the certs

I think there are two aspects 1) how to handle the expiration scenario so that the Helm keeps on working 2) the fact that `plan` will modify state of the world -> aggree to create ticket for 1), 2) is again issue for the `plan` PR

**Pull request merged**
