### PR TITLE
GPII-3590: new users, downtime procedures

### PR DESCRIPTION
**Pull request by mrtyler**
The new users and groups are created in G Suite as documented in the .md changes. [Rendered markdown USER-TRAINING](https://github.com/mrtyler/gpii-infra/blob/gpii-3590-new-users/USER-TRAINING.md), [rendered markdown downtime procedures](https://github.com/mrtyler/gpii-infra/blob/gpii-3590-new-users/gcp/README.md#downtime-procedures)

Per an earlier discussion, I'm granting all developers permissions over all dev clusters as I think this will do more good (shared communication, "let me try something on your cluster") than harm (one developer accidentally or maliciously interfering with another developer's environment). I expect this to work, but I haven't tested it yet because...

As we have discussed, testing these kinds of changes to common is tricky. Since these changes are straightforward -- copying the existing pattern for dev environments, with the caveat about group ownership mentioned above -- I'd prefer to merge this and let CI handle things. Am I missing a reason to be more cautious?

While I was in here, I added a section on downtime procedures as discussed in our last postmortem. I suspect we'll expand this documentation over time, but this is a start.

### CODE REVIEW

**Comment by stepanstipl** [comment]
> I'm granting all developers permissions over all dev clusters

I don't think this should be done via `project_owner   = "group:cloud-developers@raisingthefloor.org"`, resp. I don't think this will even work:
> The owner role can be granted only to user and serviceAccount.

See https://cloud.google.com/resource-manager/reference/rest/v1/projects/setIamPolicy

> I expect this to work, but I haven't tested it yet because...

Pls. test before merge, especially given above ^

> I added a section on downtime procedures

Cool, thanks for that! Looks good, I would propose one thing - add simple template both for opening/closing outage emails. Imho this can be as simple as:

```
Subject line: GPII [Scheduled/Completed/In progress] Production Outage - $start_date [- $end_date]

Body (plaintext please), dates in "Jan 14, 19:00 UTC" format:

What: What service(s) are affected
When: $start_data [-$end-date]
Status: [Scheduled/Completed/In progress]

Details:
Couple of lines explaining why is this planned, what is being done
and when can you expect next update.: Like "Ops team is currently
investigating the issue and we will update you once the cause is
known/issue is resolved/update is done.
```

**Comment by mrtyler** [comment]
> I don't think this will even work

AFAICT, the situation here is identical to other places, e.g. https://github.com/gpii-ops/gpii-infra/blob/master/common/live/prd/infra/prd/zone/terraform.tfvars#L25. What am I missing that is different between prd/zone and the new dev zones?

> add simple template both for opening/closing outage emails

Good idea.

**Comment by natarajaya** [comment]
LGTM!

**Comment by amatas** [comment]
LGTM

The approach that I'm following in #256 is to remove the unique owner of the "root" projects (prd, stg, dev) in favor of the inherited ownership from the organization IAMs of the group "cloud-admin".
Only the "dev-*" projects should have an owner. For the "root" projects we can grant our privileges in order to be the owner when it's needed.
The gpii-bot won't be an owner of any group anymore.
If the fact that all the developers are in one group and they would be able to perform changes in other projects, we can set one group per user. Yes, I know that can be a pain but groups are free and we can separate the privileges.

**Comment by mrtyler** [comment]
> I'm still a bit unsure whether it's a right thing to do - allowing developers to accidently destroy someone else's environment? And seems to be opposite direction to least privilege principle we're trying to implement in #256.

As engineers, we must constantly balance the Principle of Least Privilege with open communication, security with usability. To me the use cases for allowing developers to access other developers' clusters is clear: the ops team does it all the time. I'd like to see a more compelling case for locking things down before we abandon this simple way to improve cooperation between developers.

**Comment by stepanstipl** [comment]
> I'd like to see a more compelling case for locking things down before we abandon this simple way to facilitate cooperation between developers.

I for one would feel pretty uncomfortable if someone can do anything in my "personal" project.

It also has negative security implication in a sense that if someone's account gets compromised, the attacker would gain access to all the dev environemnts, instead of just one and we don't have any control over what sensitive material might be stored in these projects (ie. developer logs in to his/hers Github account, therefore leaving Github credentials behind... or some sensitive customer data...).

> we must constantly balance the Principle of Least Privilege with open communication, security with usability

I agree with this. I don't really see scenarios when one developer would need to access other developer's env and this would require direct privileges (as opposed to doing it via screenshare or smth. like that). As a developer I would probably like to be directly aware of what has been/needs to be done in my env even if it's just to make something work.

To me it's clearl improvement in security on one side and no obvious degradation of usability on another in this case. But I would like to hear more about scenarious where this would compromise usability?

**Comment by stepanstipl** [comment]
Sounds good, thanks! LGTM
> I will refer her back to this thread and we can re-visit.

I think that is a good approach - keep it consistent with current environments state and re-visit if/when we have such need.

**Pull request merged**
