### PR TITLE
GPII-2990: rake glue for exekube-based project, part 2

### PR DESCRIPTION
**Pull request by mrtyler**
This is a continuation of #33, which was merged to help Sergey. Feel free to merge this one too if it's helpful, as this code is still not exercised by CI.

For problem 3, I took Sergey's suggestion and went back to option a).

To prove that it works, I added a new environment, `live/stg`. It's a copy of `live/dev` with (so far) exactly one change -- names of DNS zones/records. In the future we may want a better way to keep environments in sync with one another (e.g. make sure that if a new component is added to dev/ that it is also added to stg/ and prd/), but for now this is pretty similar to the situation on the aws/ side.

This PR might be mergeable as-is, though it might be better to add automated calculation of `TF_VAR_project_id` first -- that's next on my todo list regardless.

### CODE REVIEW

**Comment by mrtyler** [comment]
I added TF_VAR_project_id handling. I think it mostly works. DNS entities in live/*/infra/network need updated handling (currently they are hard-coded, which is fine for stg/prd but not for dev).

**Comment by mrtyler** [comment]
This next batch of commits adds individualized DNS records (`mrtyler.dev.gcp.gpii.net`), more powerful `rake clobber`, a utility task to run arbitrary commands inside the exekube container, and the ability to re-fetch kubectl credentials after a `rake clobber`.

With this last change, it should be possible for any admin to operate `stg`, e.g. `cd live/stg && rake apply_infra`. I'm leaving the Kubernetes cluster down for now, but I left the infra component up. If you run that rake command, it should prompt you to authenticate, then terraform should run and show no changes.

**Comment by mrtyler** [comment]
Last commit removes helm-initializer (tiller) as it is no longer needed -- my incomplete couchdb chart and administration-tasks got deployed without it.

This is for GPII-2948.

**Comment by amatas** [comment]
LGTM

**Comment by natarajaya** [comment]
@mrtyler @amatas Can we please merge this AFTER #35 is reviewed?

**Comment by mrtyler** [comment]
If the question is, "Can we make it so Tyler has to deal with all the conflicts?" my vote is no. :)

If the question is, "Can we hold off on merging this to make the diffs in #35 easier to understand?" my vote is yes. (But also I'm going to do a quick test and see if git/github is smart enough to show sensible diffs even if this PR is merged before we're done looking at #35.)

**Comment by natarajaya** [comment]
@mrtyler I can deal with conflicts, no worries :) It surely is my favorite part of writing the code!
I am just a little afraid if we merge this first, it would be harder to review my changes from #35.

**Comment by mrtyler** [comment]
Since we're not merging this PR yet, I've added more changes rather than starting a new PR.

I changed the formula for TF_VAR_project_id to disambiguate between `gpii-common-prd` (managed by common/live/*; contains DNS records, IAMs, etc. shared by various environments) and `gpii-gcp-prd` (managed by gcp/live/*; contains GKE cluster, Instances, networking, etc. for the production GCP environment).

I moved an API enable from rake to gcp-project-init and submitted it to upstream: https://github.com/exekube/exekube/pull/93. If upstream takes too long to merge that change, I'll PR it to our fork instead.

Sergey thinks we still need a tiller (and his code in #35 currently requires it), so I reverted my removal of the tiller deploy for now (GPII-2948).

I think this is everything I want to do for GPII-2990, and this can be merged whenever it's not disruptive to #35.

**Comment by natarajaya** [comment]
LGTM

**Pull request merged**
