### PR TITLE
Add CircleCI config

### PR DESCRIPTION
**Pull request by natarajaya**
I tested this config with my fork and it works just fine.
GitHub checks API integration and gpii-infra project already configured on CircleCI side.

### CODE REVIEW

**Comment by mrtyler** [comment]
Can we have some documentation about the CircleCI configuration? I noticed you added an ssh key to the Organization, for example.

Perhaps it could be similar to or built upon the top section of https://github.com/gpii-ops/terraform-provider-helm/blob/master/README.md

**Comment by natarajaya** [comment]
> Can we have some documentation about the CircleCI configuration?

Sure, let me add some notes into top level README.
SSH key gets added automatically when you configure new project in CircleCI.

**Comment by natarajaya** [comment]
> It makes the links to aws/gcp/common kind of hard to spot

@mrtyler Fixed this as well.

**Comment by stepanstipl** [comment]
lgtm

**Pull request merged**
