### PR TITLE
GPII-3387 Upgrade CouchDB 2.2.0 due security vulnerabilities

### PR DESCRIPTION
**Pull request by amatas**
The https://github.com/gpii-ops/couchdb-docker/pull/2 is also needed. Although the CouchDB container is already built and tested.

I updated the chart from [the incubator](https://github.com/helm/charts/tree/master/incubator/couchdb) and added the code needed to provide the "affinity" feature from Sergey's PR: https://github.com/helm/charts/pull/7224

Since we don't have the commit history of upstream, I checked out the repository and see the differences with upstream, applying them in our branch.

### CODE REVIEW

**Comment by amatas** [comment]
I've updated the description of the PR and also the jira issue. I didn't merge the commits from upstream since we don't have the git history in this repository. The only way I found to have the changes was comparing the code of the latest version of the CouchDB helm chart from upstream with our local helm chart.

**Comment by mrtyler** [comment]
LGTM

Thanks, Alfredo. Longer term, we'll probably want a more mature release process for our Helm charts (e.g. forking the upstream charts repo directly, dedicated CI that produces a versioned chart artifact, gpii-infra consumes that artifact rather than having the chart bundled inside). Until then, documentation like this is often a life saver for the next merge.

**Comment by natarajaya** [comment]
LGTM

**Comment by stepanstipl** [comment]
Looks good

**Pull request merged**
